### ISSUE TITLE
Unable to login from ubuntu

### ISSUE THREAD

**Issue by AdithyaHS** [airavata-courses/Team-Rocket#53]
unable to login to your application from ubuntu. api broker keeps printing

 UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/media/adithya/DATA/test/Team-Rocket/APIBroker/node_modules/express/lib/response.js:1119:12)
    at ServerResponse.json (/media/adithya/DATA/test/Team-Rocket/APIBroker/node_modules/express/lib/response.js:260:14)
    at axios.then.catch (/media/adithya/DATA/test/Team-Rocket/APIBroker/api/controllers/AuthServiceCtrl.js:26:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by prathameshd** [comment]
Thanks for pointing this out. We tried running the project from scratch in an Ubuntu machine and it worked fine. Will look into this.

Curious to know what is your node version.

**Comment by aravindparappil46** [comment]
@AdithyaHS Were you able to run it?

**Comment by AdithyaHS** [comment]
@aravindparappil46 @prathameshd Thanks. Yes, I was able to run it. I am closing the issue
